### ISSUE TITLE
Error: connect ECONNREFUSED 127.0.0.1:

### ISSUE THREAD

**Issue by GitKemble** [andreasonny83/lighthouse-ci#1]
Receiving a Error: connect ECONNREFUSED 127.0.0.1:##### message when I attempt to run a lighthouse-ci test on my Windows machine. When I run regular lighthouse I do not have any issues. Was hoping you could help me. Not sure if it's a chrome flag in the config or what...

**Comment by GitKemble** [comment]
Discovered this is was due to the chromeFlags --singleProcess, once removed Windows machines work.

**Comment by GitKemble** [comment]
It would be nice to be able to pass along a few more lighthouse commands like '--disable-network-throttling' and '--disable-device-emulation'...

**Comment by andreasonny83** [comment]
Thank you @GitKemble , I'll implement that for sure

**Comment by andreasonny83** [comment]
closed by #2
