### ISSUE TITLE
LightHouse CI unable to audit sites with a broken SSL certificate.

### ISSUE THREAD

**Issue by nikilok** [andreasonny83/lighthouse-ci#15]
When a web page is on an https URL with an invalid SSL certificate lighthouse ci generates a report file with the following message.

> There were issues affecting this run of Lighthouse:
Lighthouse was unable to reliably load the page you requested. Make sure you are testing the correct URL and that the server is properly responding to all requests. net::ERR_CERT_AUTHORITY_INVALID.

Is there a way to tell lighthouse to ignore the SSL issues and continue loading the page?
![image](https://user-images.githubusercontent.com/6220175/47211528-f5123880-d395-11e8-8cd9-766b860d17ee.png)

**Comment by andreasonny83** [comment]
@nikilok you can probably ignore that using an `http` URL rather than `https`. Otherwise try asking the Lighthouse team at https://github.com/GoogleChrome/lighthouse. 
There's no much I can do about that as lighthouse-ci is just a wrapper around the Google Lighthouse project.

**Comment by dcheng168** [comment]
I'm experiencing the same issue here but `http` is not an option for me.

I found it can be done with the following chrome flag with Google `lighthouse`:
`--chrome-flags='--ignore-certificate-errors'`

@andreasonny83 Please correct me if I misunderstood anything here. It seems `lighthouse-ci` doesn't support updating `chromeFlags` with cmd line args yet.  Is there any plan for this?
