### ISSUE TITLE
Best practice still passes when threshold is exceeded

### ISSUE THREAD

**Issue by dancowen** [andreasonny83/lighthouse-ci#16]
lighthouse-ci https://bbc.co.uk --accessibility=90 --seo=80 --pwa=58 --performance=30 --best-practice=88

performance: 40
pwa: 58
accessibility: 100
best-practices: 87
seo: 100
All checked scores are passing. 🎉

**Comment by andreasonny83** [comment]
Thanks @dancowen . I'll investigate this ASAP
