### ISSUE TITLE
Useful but would like to crawl site & build CSV

### ISSUE THREAD

**Issue by mgifford** [andreasonny83/lighthouse-ci#17]
I want to know which pages of my site are a problem.  Crawl the site on a daily basis and find which pages do not meet my requirements.  This seems hard to do with lighthouse.

**Comment by mgifford** [comment]
Starting to think that a crawl may not be as useful as I think, but still it would be a nice option. Maybe if I could get lightcrawler working.

**Comment by andreasonny83** [comment]
well Lighthouse it's very powerful when using SinglePageApplications but you can run Lighthouse against different pages (URLs).
i'm closing this as it seems to be more a feedback rather than an issue. You can still ask this question to the Google team on https://github.com/GoogleChrome/lighthouse
