### ISSUE TITLE
TypeError: Cannot read property 'split' of undefined

### ISSUE THREAD

**Issue by naltatis** [andreasonny83/lighthouse-ci#24]
I've upgraded to v1.4.0 but now I'm getting the error `TypeError: Cannot read property 'split' of undefined` and the test aborts.

Im running this:
```
npx lighthouse-ci --performance=85 --accessibility=70 --best-practices=80 --seo=95 --report=./ https://example.org
```

When I add an empty `--chrome-flags=` parameter it works.

**Comment by andreasonny83** [comment]
Thanks for reporting that @naltatis . I think I know the reason for that error. I'm working on it and you should be able to use a new v1.4.1 soon

**Comment by andreasonny83** [comment]
https://github.com/andreasonny83/lighthouse-ci/releases/tag/v1.4.1
