### ISSUE TITLE
dont hard code report.html

### ISSUE THREAD

**Issue by fadomire** [andreasonny83/lighthouse-ci#25]
Hello, thanks for the lib !

would it be possible to allow choosing the name of the html report ?
currently it is hard coded to report.html

thanks

**Comment by andreasonny83** [comment]
Hi @fadomire 
I'll try to look into it but if you have the time to create a pull request, it would be great

**Comment by fadomire** [comment]
@andreasonny83 hi 
sure when this get backs on my todo i’ll make a PR
currently the lighthouse part of my project is in standby

**Comment by andreasonny83** [comment]
Closed by #27
