### ISSUE TITLE
How to evaluate all urls of a website?

### ISSUE THREAD

**Issue by nianxiongdi** [andreasonny83/lighthouse-ci#26]

**Comment by andreasonny83** [comment]
Can you please articulate your request?
I don't think it's possible to fetch a list of website urls in the first place. I can only think about a `sitemap` file but not all the websites have one by default.
If you know of a possible way for doing that, maybe you can add more description to the ticket or create a pull request

**Comment by lastcosmonaut** [comment]
Maybe passing multiple urls? *shrug*
lighthouse-batch enables this.

**Comment by andreasonny83** [comment]
@nianxiongdi .
I decided not to proceed with this issue request as you can simply sequentially run lighthouse-ci against your domains, from your terminal.
