### ISSUE TITLE
lighthouse flag ignored

### ISSUE THREAD

**Issue by grebenyuksv-preply** [andreasonny83/lighthouse-ci#31]
Dear maintainers, I'm trying to set up my performance budgets, and the native `--budget-path=lh/budget.json` flag doesn't seem to be passed to Lighthouse.

**Repro steps:**
```
lighthouse-ci --budget-path=lh/budget.json https://preply.com/en/teach --report=lh
```
or as well
```
lighthouse-ci https://preply.com/en/teach --budget-path=lh/budget.json --report=lh
```

**Expected result:**
`lh/report.html` containing section "Budgets — Performance budgets set standards for the performance of your site", similarly to what calling bare Lighthouse returns: 
```
lighthouse https://preply.com/en/teach --budget-path=lh/budget.json --output-path=lh/report.html
```

**Actual result:**
No occurrences of "budget" in the report.

Please tell me if I can provide you with any additional info. I did read https://github.com/andreasonny83/lighthouse-ci/pull/19, but it didn't help.

**Comment by foray1010** [comment]
I was going to open a similar issue! I think the config is not ignored, it doesn't throw error even if you pass the budget via `config-path`, it is just because the code doesn't implement performance-budget checking (see https://github.com/andreasonny83/lighthouse-ci/blob/master/bin/cli#L181-L202)

`lighthouse` just response result in json format, but it is up to `lighthouse-ci` to parse it and response to user

**Comment by andreasonny83** [comment]
Thanks, both @grebenyuksv-preply and @foray1010 .
I'm sorry about the unexpected behaviour. I'll try to have a look as soon as I have time and release a patch for the cli.
Alternatively, if you can create a PR with that fix, I'll be more than happy to review it. That will speed up the releasing process for sure.

Thanks again

**Comment by asmagin** [comment]
`--budget-pass` is passed but is it not working as a parameter when you are using lighthouse from code
As of now, you can pass budget configurations as a part of configs like:
```
{
  "extends": "lighthouse:default",
  "settings": {
    "budgets": [
      {
        "resourceCounts": [
          { "resourceType": "total", "budget": 10 },
          
        ],
        "resourceSizes": [
          { "resourceType": "total", "budget": 100 },
        ]
      }
    ]
  }
}
```

**Comment by grebenyuksv-preply** [comment]
@asmagin fantastic, it worked! I didn't manage to figure that way out from LH docs. 

Feel free to close the issue if it makes sense to you.
