### ISSUE TITLE
How to test page after authentication required?

### ISSUE THREAD

**Issue by SharkBaby** [andreasonny83/lighthouse-ci#40]
I want to run lighthouse-cli my-account page which need to authentication required, I found it will redirect to login page, May I know how to fill authentication for lighthouse-cli?
![image](https://user-images.githubusercontent.com/18545909/60073617-8458c280-9753-11e9-8bef-c11f2d1dcfbb.png)

**Comment by andreasonny83** [comment]
Hi @SharkBaby .
It is actually possible. Please refer to https://github.com/andreasonny83/lighthouse-ci/#test-a-page-that-requires-authentication
