### ISSUE TITLE
Unable to generate report

### ISSUE THREAD

**Issue by vanntastic** [andreasonny83/lighthouse-ci#46]
Hi - I can't seem to generate a report from lighthouse-ci, I'm passing the report and filename flag (and I've also tried it without the filename flag) when I run it, it tells me the that file or directory doesn't exist:
![image](https://user-images.githubusercontent.com/9515/62167763-8b8e6580-b2e9-11e9-90e7-e4e9216c6418.png)
is there something that I'm missing? thanks!

**Comment by itsmarcio** [comment]
I'm seeing the same issue. Something that worked for me was to run it again but with `--report=` (this will fail), and then run again with `--report set to whatever folder you have. Hope it works for you!

**Comment by andreasonny83** [comment]
Sorry about the late response @itsmarcio .
The problem could be related to the fact that the `report` folder does not exist. The CLI is just responsible for creating the final `report.html` file, so the folder must exist on your location already. Try creating an empty `report` folder first, then run Lighthouse-CI again.

Thanks

**Comment by andreasonny83** [comment]
Closing this one as resolved
