### ISSUE TITLE
Cannot read property 'lhr' of undefined

### ISSUE THREAD

**Issue by luckyraul** [andreasonny83/lighthouse-ci#49]
lighthouse-ci --gather-mode=test-result $DOMAIN
- Running Lighthouse on https://www.domain.com ...

TypeError: Cannot read property 'lhr' of undefined

**Comment by andreasonny83** [comment]
Thanks @luckyraul 
The latest version of Lighthouse-CI should now give you the correct error message.
Feel free to reopen if now
