### ISSUE TITLE
Would you consider supporting lighthouse plugins?

### ISSUE THREAD

**Issue by mrchrisadams** [andreasonny83/lighthouse-ci#52]
Hi there, 

I'm working on a lighthouse plugin, which checks the domain for every resources requested on a page, against a database that tells if you if they run on renewable energy, to give a score out of a hundred, like so if you have a clean sheet.

It's called greenhouse (lighthouse, but green… geddit?) and when it works, it looks like this:

![Screenshot 2019-08-06 at 20 19 47](https://user-images.githubusercontent.com/17906/62565679-93b94880-b887-11e9-95aa-d620d004b784.png)

### Making it work with lighthouse CI

I want to make this work with Lighthouse CI, so anyone using lighthouse CI can also run these checks - I figure if you're working in field like web development, it's reasonable you might think that science, and in particular the science around climate change is worth doing something about. 

However, when I run lighthouse-ci, and pass in a `plugins` flag, like so:

```
npx lighthouse-ci http://google.com --plugins=lighthouse-plugin-greenhouse
```

I get an error along the lines of:

```
Error: plugin name 'l' does not start with 'lighthouse-plugin-'
```

I think this because in [`launchChromeAndRunLighthouse`](https://github.com/andreasonny83/lighthouse-ci/blob/master/lib/lighthouse-reporter.js#L18), when we pass in the lighthouse native plugins, lighthouse is expecting an array for the `plugins` flag:

```
const flags = {
    port: chrome.port,
    output: 'json',
    ...lighthouseFlags,
  };
``` 

I've been able to fix this in a test with a _very_ naive snippet of code (don't worry, I'll totally change this to be less janky), 

```
const checkFlagsForPlugins = obj => {
  if (obj['plugins']) {
    obj.plugins = [obj.plugins]
  }
  return obj
}
```

But before I tidy up the change up into a pull request, I figure it's worth asking, as I think I need a few pointers for making the PR support plugins properly in lighthouse CI.

You can see the output at the bottom in my working branch, where the name of the plugin is used verbatim, and it would be nice to give a nicer one, as lighthouse enforces a naming convention in the plugin name, which you see below:

```
Running Lighthouse on http://google.com ...
performance: 86
accessibility: 78
best-practices: 79
seo: 92
pwa: 48
lighthouse-plugin-greenhouse: 100
All checks are passing. 🎉
```

It's not just my plugin that would benefit from this. There's another plugin that works by checking your site against a sample of real world usage too, that this would enable:

https://github.com/treosh/lighthouse-plugin-field-performance

### Getting some pointers:

So, here are my questions:

- is I've added a plugin adapter in the helpers file in the PR - I'll tidy up the code in a bit, but is this an okay place to put it
- it would be good to support a more sensible name than `lighthouse-plugin` for plugin names
- if I wanted to support setting budgets for plugins in future, where would I look to see what to extend to support?

Here's the corresponding pull request for this issue:

https://github.com/andreasonny83/lighthouse-ci/pull/51

**Comment by andreasonny83** [comment]
Please, reopen if you make any progress
