### ISSUE TITLE
Return non-zero exit code on failure

### ISSUE THREAD

**Issue by joelcox** [andreasonny83/lighthouse-ci#6]
Thanks for your great package! I was putting it through its paces and noticed that cli.js does not return a non-zero exit code when a test does not pass. It does explicitly return 0 when it succeeds. I'm not sure if this is by design, but many CI tools return `1` to indicate failure of a job.

My suggestion would be to add `return process.exit(1)` when the promise in cli.js rejects (possibly [here](https://github.com/andreasonny83/lighthouse-ci/blob/master/lib/cli.js#L132)

**Comment by andreasonny83** [comment]
Thank you @joelcox, the newer version 1.1.1 will contain that bug fix.
