### ISSUE TITLE
lighthouse-ci doesn't explain why it failed

### ISSUE THREAD

**Issue by elgalu** [andreasonny83/lighthouse-ci#60]
Hi, thanks for this great tool!

`lighthouse-ci` doesn't explain why it failed

```
accessibility: 92
best-practices: 86
seo: 100
pwa: 77
Failed. ❌

Error: lighthouse-ci test failed.
```

It would be nice to output per line failed assertions, e.g. failed due to `pwa < 80`

**Comment by andreasonny83** [comment]
Thanks for reporting this @elgalu 
I'll try to add more messages. However, PRs are always welcome if you want to contribute
