### ISSUE TITLE
No summary table

### ISSUE THREAD

**Issue by mbrodala** [andreasonny83/lighthouse-ci#62]
I might be missing something but I do not get the summary table shown in the README cast:

<img src="https://raw.githubusercontent.com/andreasonny83/lighthouse-ci/master/lighthouse-cli.gif" width="700">

Instead all I get is this:

```
$ lighthouse-ci http://apache/
All checks are passing. 🎉
```

Also I always get a failure, even with a score of 1:

```
 lighthouse-ci --score=1 http://apache/
Failed. ❌

Error: lighthouse-ci test failed.
```

(Here `http://apache/` is the internal host name of an Apache service within a Docker network.)

Strangely this seems to work fine for public URLs:

```
$ lighthouse-ci https://example.org
performance: 100
accessibility: 88
best-practices: 100
seo: 90
pwa: 48
All checks are passing. 🎉
```

Is there a way to enable some verbose mode to see what happens internally?

**Comment by mbrodala** [comment]
OK, I just solved it. Apparently this is the same issue as #56 since my site was throwing a 500 error and this was not reported in any way.

I agree that this should lead to a proper error message.

**Comment by andreasonny83** [comment]
Acknowledged, thank you.
I will try to improve that part
