### ISSUE TITLE
remove snyk as a direct project dependency

### ISSUE THREAD

**Issue by krohrsb** [andreasonny83/lighthouse-ci#70]
Snyk as a direct dependency brings in a whole slew of stuff that you likely don't want in a production bundle tree. Suggest moving it to devDependencies so it doesn't get published to npm.

https://github.com/andreasonny83/lighthouse-ci/commit/7b74e4cea7a9dae1dfd3c8c7d1330ed0a8cba287

I'm not sure why snyk applies itself as a production dependency...

**Comment by andreasonny83** [comment]
Thanks for reporting this. I think Snyk was added as direct dependency by mistake. I'll move that under `devDependencies`
Thank you
