### ISSUE TITLE
Failing when scores = 100

### ISSUE THREAD

**Issue by craigiswayne** [andreasonny83/lighthouse-ci#8]
Hi Andrea, thank you so much for this package! it is incredibly useful :)

Just noticed something using this, see the below scenario:

![screen shot 2018-09-30 at 13 01 16](https://user-images.githubusercontent.com/5500952/46256896-8e45e180-c4b1-11e8-8480-7dbc213fe7d1.png)

Found that if i changed this file [/lib/cli.js:113](https://github.com/andreasonny83/lighthouse-ci/blob/master/lib/cli.js#L113)

to the following:
```javascript
let thresholds = scoreReducer(cli.flags, getScores());
thresholds = 0 === Object.keys(thresholds).length ? {score:100} : thresholds;
```

then i get the following:

![screen shot 2018-09-30 at 13 07 30](https://user-images.githubusercontent.com/5500952/46256914-cf3df600-c4b1-11e8-8f2e-3c4c3a2b1d0f.png)

So it seems like when no flags are passed, the thresholds object is empty, and thus skips past this check (because the thresholds object is actual empty):

```javascript
    if (thresholds && Object.keys(thresholds).length !== 0) {
      const isScorePassing = analizeScore(categoryReport, thresholds);

      if (isScorePassing) {
        console.log(chalk.green('All checked scores are passing. 🎉\n'));
        return process.exit(0);
      }
    }
```

**Comment by 9reeno** [comment]
How do I go about building from source so that I can test these changes? Thanks.
