### ISSUE TITLE
Error on Jenkins, Protocol error (Fetch.disable)

### ISSUE THREAD

**Issue by yacafx** [andreasonny83/lighthouse-ci#83]
I ran `npx lighthouse-ci https://medium.com` on a Jenkins pipeline but threw the next error.
```
- Running Lighthouse on https://www.medium.com ...

Error: Protocol error (Fetch.disable): 'Fetch.disable' wasn't found
Error: exec: - Running Lighthouse on https://www.medium.com ...
```

When I downgrade the version, the error is not happening.  

Can you help with this?

**Comment by andreasonny83** [comment]
@yacafx what version of Node are you using.
Please, make sure you're at least on v10

**Comment by andreasonny83** [comment]
This error is actually coming from Google Lighthouse directly: https://github.com/GoogleChrome/lighthouse/issues/11596
