### ISSUE TITLE
TypeError: categoryIds.forEach is not a function

### ISSUE THREAD

**Issue by jeffochoa** [andreasonny83/lighthouse-ci#84]
Hello there 👋

I'm getting `TypeError: categoryIds.forEach is not a function` when I try to use the `--only-categories` flag:

```bash
lighthouse-ci https://jeffochoa.me --only-categories=seo,performance,accessibility,best-practices
```

Any Ideas?

**Comment by andreasonny83** [comment]
@jeffochoa what node version are you using. Please, make sure to have at least Node v10 installed

**Comment by wolasss** [comment]
I am having the same issue and I am using node v14
