### ISSUE TITLE
Allow custom lighthouse configuration file

### ISSUE THREAD

**Issue by minorOffense** [andreasonny83/lighthouse-ci#9]
I'd like to make a feature request to allow this tool to pass through some configuration options to lighthouse itself. I think the easiest way would be just allow the ``--config-path`` flag to pass to lighthouse.

For example we want to optimize some of our tests in lighthouse so we use the ``--gather-mode`` to collect artifacts from a connected browser and save to disk first. Then we run our audits against that saved collection. We run a lot of different tests as part of our build in different phases and this saves us from having to download the site pages over and over again.

Anyways let me know if you're interested in this type of functionality. I can likely write a patch to have it do so.

Thanks!

**Comment by celsosantarosa** [comment]
Or at least, allow us to pass the lighthouse CLI flags through the command line.

**Comment by andreasonny83** [comment]
That would be great. It would be even better if you can create a Pull Request for that @celsosantarosa 😄

**Comment by celsosantarosa** [comment]
Done. Could you review the PR please?

**Comment by andreasonny83** [comment]
closed in #19
